#!/bin/sh

cd $HOME

sudo apt update && sudo apt upgrade -y
sudo apt install -y build-essential libssl-dev libclang-dev cmake jq keychain zsh
sudo apt autoremove -y
sudo apt autoclean -y
sudo apt clean -y

[ "$SHELL" = "/bin/zsh" ] || chsh -s /bin/zsh
[ -e "$HOME/.ssh/id_ed25519" ] || ssh-keygen -a 128 -f "$HOME/.ssh/id_ed25519" -C "kuhakuspace2000@gmail.com"
[ -e "$HOME/.ssh/signing-key" ] || ssh-keygen -a 128 -f "$HOME/.ssh/signing-key" -C "kuhakuspace2000@gmail.com"
tail -n 1 /etc/zsh/zshenv | grep -vq "export ZDOTDIR" && echo "\nexport ZDOTDIR=$HOME/.config/zsh" | sudo tee -a /etc/zsh/zshenv
. $HOME/.config/zsh/.zshenv
command -v mise >/dev/null || curl https://mise.run | sh
command -v bat >/dev/null || mise u --global bat
command -v deno >/dev/null || mise u --global deno
command -v fzf >/dev/null || mise u --global fzf
command -v ghq >/dev/null || mise u --global ghq
command -v zoxide >/dev/null || mise u --global zpxide
command -v cargo >/dev/null || mise u --global rust
mise up
cargo install sheldon starship zoxide
exec $SHELL -l
