snippets:
  - name: update and upgrade packages
    keyword: apt-up
    snippet: sudo apt update && sudo apt upgrade -y
  - name: eza
    keyword: l
    snippet: eza -lha --icons --group-directories-first
  - name: yadm
    keyword: y
    snippet: yadm
  - name: git
    keyword: g
    snippet: git
  - name: git push
    keyword: ps
    snippet: push
    context:
      lbuffer: ^git\s
  - name: git pull
    keyword: pl
    snippet: pull
    context:
      lbuffer: ^git\s
  - name: git checkout
    keyword: co
    snippet: checkout
    context:
      lbuffer: ^git\s
  - name: git branch
    keyword: br
    snippet: branch
    context:
      lbuffer: ^git\s
  - name: git status
    keyword: st
    snippet: status
    context:
      lbuffer: ^git\s
  - name: git switch
    keyword: sw
    snippet: switch
    context:
      lbuffer: ^git\s
  - name: git switch -c
    keyword: swc
    snippet: switch -c
    context:
      lbuffer: ^git\s
  - name: git switch -c feature/
    keyword: f
    snippet: feature/
    context:
      lbuffer: ^git\sswitch\s-c\s
  - name: git commit message
    keyword: cm
    snippet: commit -m '{{commit_message}}'
    context:
      lbuffer: ^git\s
