[tools]
bat = "latest"
deno = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
glow = "latest"
hyperfine = "latest"
neovim = "latest"
rust = "latest"
starship = "latest"
yadm = "latest"
zoxide = "latest"
claude = "latest"
usage = "latest"
node = "latest"
jujutsu = "latest"
sheldon = "latest"
zellij = "latest"
